import { CurrencyCode, CurrencyMetadata } from '@/types/locale';

/**
 * Currency metadata for African fiat and stablecoins
 */
export const CURRENCY_METADATA: Record<CurrencyCode, CurrencyMetadata> = {
  NGN: {
    code: 'NGN',
    symbol: '₦',
    name: 'Nigerian Naira',
    subUnit: 'Kobo',
    subUnitDivision: 100,
    minFractionDigits: 2,
    maxFractionDigits: 2,
    symbolPosition: 'before',
    isCrypto: false,
  },
  KES: {
    code: 'KES',
    symbol: 'KSh',
    name: 'Kenyan Shilling',
    subUnit: 'Cent',
    subUnitDivision: 100,
    minFractionDigits: 2,
    maxFractionDigits: 2,
    symbolPosition: 'before',
    isCrypto: false,
  },
  GHS: {
    code: 'GHS',
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
    subUnit: 'Pesewa',
    subUnitDivision: 100,
    minFractionDigits: 2,
    maxFractionDigits: 2,
    symbolPosition: 'before',
    isCrypto: false,
  },
  ZAR: {
    code: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    subUnit: 'Cent',
    subUnitDivision: 100,
    minFractionDigits: 2,
    maxFractionDigits: 2,
    symbolPosition: 'before',
    isCrypto: false,
  },
  USDC: {
    code: 'USDC',
    symbol: 'USDC',
    name: 'USD Coin',
    subUnit: 'Stroop',
    subUnitDivision: 10000000,
    minFractionDigits: 2,
    maxFractionDigits: 7,
    symbolPosition: 'after',
    isCrypto: true,
  },
  EURC: {
    code: 'EURC',
    symbol: 'EURC',
    name: 'Euro Coin',
    subUnit: 'Stroop',
    subUnitDivision: 10000000,
    minFractionDigits: 2,
    maxFractionDigits: 7,
    symbolPosition: 'after',
    isCrypto: true,
  },
  XLM: {
    code: 'XLM',
    symbol: 'XLM',
    name: 'Stellar Lumens',
    subUnit: 'Stroop',
    subUnitDivision: 10000000,
    minFractionDigits: 2,
    maxFractionDigits: 7,
    symbolPosition: 'after',
    isCrypto: true,
  },
};
